# Generated by Django 2.2.2 on 2019-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenthicSurvey',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Transect_ID', models.IntegerField()),
                ('Benthic_category', models.CharField(max_length=20)),
                ('Total_cover', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BenthicSurvey_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_transect_ID', models.IntegerField()),
                ('Enter_benthic_category', models.CharField(max_length=20)),
                ('Enter_total_cover', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FishSurvey_data',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Trans_ID', models.IntegerField()),
                ('Name_Local', models.CharField(max_length=20)),
                ('Total_Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invert_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransID', models.IntegerField()),
                ('Name_Invert', models.CharField(max_length=20)),
                ('No_Invert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lookup_Benthic',
            fields=[
                ('Name_Local', models.CharField(max_length=30)),
                ('Abbrv', models.CharField(max_length=5)),
                ('Name_Common', models.CharField(max_length=30)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lookup_Fish',
            fields=[
                ('Name_Local', models.CharField(max_length=30)),
                ('Name_Common', models.CharField(max_length=30)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Scientific_N', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lookup_Invert',
            fields=[
                ('Name_Local', models.CharField(max_length=30)),
                ('Name_Common', models.CharField(max_length=30)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lookup_Site',
            fields=[
                ('SiteName', models.CharField(max_length=20)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('GPS_X', models.IntegerField()),
                ('GPS_Y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Info',
            fields=[
                ('TransID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Data_Collector', models.CharField(max_length=30)),
                ('Site_Name', models.CharField(max_length=20)),
                ('Trans_No', models.IntegerField()),
                ('Date_Survey', models.DateTimeField(verbose_name='date surveyed')),
            ],
        ),
    ]
