# Generated by Django 2.2.2 on 2019-06-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenthicSurvey',
        ),
    ]
